### PR TITLE
Update autoconf m4 macros, removing warnings about obsolete macros

### PR DESCRIPTION
**Pull request by mywave82**
ESD upstream is dead
libao upstream maybe is alive?

### CODE REVIEW

**Comment by mywave82** [comment]
Will try to upstream libao, but that project is likely dead, since they have PRs that have been there for years

**Comment by Malvineous** [comment]
Apparently there was a libao release only a couple of days ago: https://xiph.org/ao/

**Comment by Malvineous** [comment]
Oops never mind, I read 2014 as 2024 :-/

**Comment by mywave82** [comment]
> Oops never mind, I read 2014 as 2024 :-/

The unstoppable marching of time...

**Comment by mywave82** [comment]
https://gitlab.xiph.org/xiph/libao/-/merge_requests/9

**Comment by mywave82** [comment]
Since upstream is likely dead, I added some information in the header that the files are modified by us.

**Comment by Malvineous** [comment]
All good with me, happy for it to be merged

**Pull request merged**
