### PR TITLE
autoconf / m4 update

### PR DESCRIPTION
**Pull request by mywave82**
* Split up acinclude.m4 into separate m4 files makes it easier to maintain
* update the .m4 files
* Add regen.sh for persons who are not experient in automake/autoconf

This is one of the details pointed out in #23 by @dmitrysmagin

### CODE REVIEW

**Comment by Malvineous** [comment]
Is `regen.sh` better than running `autoreconf`?

**Comment by mywave82** [comment]
> Is `regen.sh` better than running `autoreconf`?

I followed a guide that probably was outdated, but which commands autoreconf implies probably depends on the version of it, and considering we have bugreports about gcc 4.x toolchain issues in adplug I guess it didn't hurt.

**Comment by mywave82** [comment]
Also autoreconf fails if you are changing m4 stuff and already have existing Makefile. Then you either need to purge manually or run the commands manually as implied in ./regen.sh

**Comment by Malvineous** [comment]
Interesting, fair enough.  I'm no expert but I assumed autoreconf was supposed to avoid the need for a shell script, but if it doesn't work, then I have no problem with the shell script.

The main AdPlug readme has for a long time suggested to run `autoreconf --install` - I presume that doesn't fare any better in those situations you mention?

**Comment by mywave82** [comment]
autoreconf --install should work for most use-cases, but if there any failures or autotools stop working while hacking on it, the steps inside ./regen.sh should get you back on-track

**Comment by mywave82** [comment]
Just merged info from regen.sh into README instead

**Pull request merged**
